Script started on Thu Sep  3 18:51:04 2020

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
[?1034hbash-3.2$ cat Mae[Kkefile [K; cat a1.c; cat a11.c; ./a1; ./a11
#################################################################
# Read the handout makeandmakefile.pdf for details.
# variables, flags for CFLAGS
# -Wall flags all errors
# -Werror treats warning as an error
# -g  includes symbol table to help gdb
#
# ****** do not change the CFLAGS line **** 
#
#################################################################
CFLAGS  = -g -Wformat-security -Wall
LDFLAGS =  -lpthread
CC	= gcc
LD	= gcc

TARG	= a11

OBJS    = a11.o

#################################################################
# rules:
# indented lines have a tab (^I) at the start of line!!
#################################################################

$(TARG): $(OBJS)
	$(LD) $(OBJS) $(LDFLAGS) -o $(TARG)

%.o: %.c
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f *.o $(TARG) a.out 

#################################################################
# dependencies -- none in this program
#################################################################
#include <stdio.h>
#include <stdlib.h>

/* Find the largest integer in array */
int largest(int d[], int size);

/* Find the smallest integer in the array */
int smallest(int d[], int size);

/* Find the average integer in the array */
int average(int d[], int size);

/* Print the data set */
void printdata(int d[], int size);

/* Print the results from the data */
void printrslts(int largest, int smallest, int average);

/* Entry point of program */
int main(void) {

    // Declare data set as an array of integers
    int data[11] = { 1, 2, 3, -3, -99, 999, 42, 14, 56, 76, 99 };
    int size;

    size = 11;

    if (size > 0) {
        int largestNum = largest(data, size);
        int smallestNum = smallest(data, size);
        int averageNum = average(data, size);

        /* Print dataset */
        printdata(data, size);

        /* Print results */
        printrslts(largestNum, smallestNum, averageNum);
    }
    
    exit(0);
}
/*
 *  Function:    largest
 *  ------------------------------------
 *  Iterates through the input array, and finds the largest
 *  number.
 *
 *  d[]: an array of integers to search
 *  size: the size of array d[]
 *
 *  returns: the largest integer contained within d[]
 */
int largest(int d[], int size) {
    int largestNum = d[0];

    for (int i = 0; i < size; i++) {
        if (d[i] > largestNum) {
            largestNum = d[i];
        }
    }

    return largestNum;
}

/*
 *  Function:   smallest
 *  ------------------------------------
 *  Iterates through the input array, and finds the smallest
 *  number.
 *
 *  d[]: an array of integers to serach
 *  size: the size of array d[]
 *
 *  returns: the smallest integer contained within d[]
 */ 
int smallest(int d[], int size) {
    int smallestNum = d[0];

    for (int i = 0; i < size; i++) {
        if (d[i] < smallestNum) {
            smallestNum = d[i];
        }
    }

    return smallestNum;
}

/*
 *  Function:   average
 *  ------------------------------------
 *  Iterates through the input array, and computes
 *  the average number. Computation is as follows:
 *      sum of all numbers / size of array
 *
 *  d[]: an array of integers to compute the average from
 *  size: the size of array d[]
 *
 *  returns: the average number as computed from the array
 */
int average(int d[], int size) {
    int sum = 0;

    for (int i = 0; i < size; i++) {
        sum += d[i];
    }

    return sum / size;
}

/*
 *  Function:   gtrAverage
 *  ------------------------------------
 *  Iterates through the input array, and computes
 *  a count of numbers that are greater than the
 *  average number.
 *
 *  d[]: an array of integers to collect count from
 *  size: the size of array d[]
 *
 *  returns: a count of numbers that are greater than
 *           the provided average
 */
int gtrAverage(int d[], int size, int average) {
    int count = 0;

    for (int i = 0; i < size; i ++) {
        if (d[i] > average) {
            count += 1;
        }
    }

    return count;
} 


/*
 *  Function:   printdata
 *  ------------------------------------
 *  Prints the provided dataset in a readable 
 *  format. Every number is right justified, with
 *  8 spaces between.
 *
 *  d[]: an array of integers to print
 *  size: the size of array d[]
 *
 *  returns: void
 */ 
void printdata(int d[], int size) {
    printf("Data: ");
    for (int i = 0; i < size; i++) {
        printf("%8d ", d[i]);
    }

    printf("\n");
}

/*
 *  Function:   printrslts
 *  ------------------------------------
 *  Prints the results from the computations
 *  of the dataset. Labels are left justified
 *  with 20 spaces and results are right justified
 *  with 20 spaces.
 *
 *  largset:            an integer representing the largest number
 *  smallest:           an integer representing the smallest number
 *  average:            an integer representing the average
 *
 *  returns: void
 */ 
void printrslts(int largest, int smallest, int average) {
    printf("\nResults:\n");
    printf("%-20s%20d\n", "Largest Int: ", largest);
    printf("%-20s%20d\n", "Smallest Int: ", smallest);
    printf("%-20s%20d\n", "Average Int: ", average);
}
#include <stdio.h>
#include <stdlib.h>

/* Find the largest integer in array */
int largest(int d[], int size);

/* Find the smallest integer in the array */
int smallest(int d[], int size);

/* Find the average integer in the array */
int average(int d[], int size);

/* Print the data set */
void printdata(int d[], int size);

/* Print the results from the data */
void printrslts(int largest, int smallest, int average);

/* Entry point of program */
int main(void) {
    int data[11] = { 1, 2, 3, -3, -99, 999, 42, 14, 56, 76, 99 };
    int size;

    size = 11;

    if (size > 0) {
        int largestNum = largest(data, size);
        int smallestNum = smallest(data, size);
        int averageNum = average(data, size);

        /* Print dataset */
        printdata(data, size);

        /* Print results */
        printrslts(largestNum, smallestNum, averageNum);

        printf("%-30s%-20p\n", "Address of main(): ", main);
        printf("%-30s%-20p\n", "Address of data[]: ", data);
        printf("%-30s%-20p\n", "Address of size: ", &size);
        printf("%-30s%-20p\n", "Address of largest(): ", largest);
        printf("%-30s%-20p\n", "Address of largestNum: ", &largestNum);
        printf("%-30s%-20p\n", "Address of smallest(): ", smallest);
        printf("%-30s%-20p\n", "Address of smallestNum: ", &smallestNum);
        printf("%-30s%-20p\n", "Address of average(): ", average);
        printf("%-30s%-20p\n", "Address of averageNum: ", &averageNum);
        printf("%-30s%-20p\n", "Address of printdata(): ", printdata);
        printf("%-30s%-20p\n", "Address of printrslts(): ", printrslts);
    }
    
    exit(0);
}
/*
 *  Function:    largest
 *  ------------------------------------
 *  Iterates through the input array, and finds the largest
 *  number.
 *
 *  d[]: an array of integers to search
 *  size: the size of array d[]
 *
 *  returns: the largest integer contained within d[]
 */
int largest(int d[], int size) {
    int largestNum = d[0];

    for (int i = 0; i < size; i++) {
        if (d[i] > largestNum) {
            largestNum = d[i];
        }
    }

    return largestNum;
}

/*
 *  Function:   smallest
 *  ------------------------------------
 *  Iterates through the input array, and finds the smallest
 *  number.
 *
 *  d[]: an array of integers to serach
 *  size: the size of array d[]
 *
 *  returns: the smallest integer contained within d[]
 */ 
int smallest(int d[], int size) {
    int smallestNum = d[0];

    for (int i = 0; i < size; i++) {
        if (d[i] < smallestNum) {
            smallestNum = d[i];
        }
    }

    return smallestNum;
}

/*
 *  Function:   average
 *  ------------------------------------
 *  Iterates through the input array, and computes
 *  the average number. Computation is as follows:
 *      sum of all numbers / size of array
 *
 *  d[]: an array of integers to compute the average from
 *  size: the size of array d[]
 *
 *  returns: the average number as computed from the array
 */
int average(int d[], int size) {
    int sum = 0;

    for (int i = 0; i < size; i++) {
        sum += d[i];
    }

    return sum / size;
}

/*
 *  Function:   gtrAverage
 *  ------------------------------------
 *  Iterates through the input array, and computes
 *  a count of numbers that are greater than the
 *  average number.
 *
 *  d[]: an array of integers to collect count from
 *  size: the size of array d[]
 *
 *  returns: a count of numbers that are greater than
 *           the provided average
 */
int gtrAverage(int d[], int size, int average) {
    int count = 0;

    for (int i = 0; i < size; i ++) {
        if (d[i] > average) {
            count += 1;
        }
    }

    return count;
} 


/*
 *  Function:   printdata
 *  ------------------------------------
 *  Prints the provided dataset in a readable 
 *  format. Every number is right justified, with
 *  8 spaces between.
 *
 *  d[]: an array of integers to print
 *  size: the size of array d[]
 *
 *  returns: void
 */ 
void printdata(int d[], int size) {
    /* printf("Data: ");*/
    for (int i = 0; i < size; i++) {
        /* printf("%8d ", d[i]); */
    }

    /* printf("\n"); */
}

/*
 *  Function:   printrslts
 *  ------------------------------------
 *  Prints the results from the computations
 *  of the dataset. Labels are left justified
 *  with 20 spaces and results are right justified
 *  with 20 spaces.
 *
 *  largset:            an integer representing the largest number
 *  smallest:           an integer representing the smallest number
 *  average:            an integer representing the average
 *
 *  returns: void
 */ 
void printrslts(int largest, int smallest, int average) {
    /* printf("Results:\n");
    printf("%-20s%20d\n", "Largest Int: ", largest);
    printf("%-20s%20d\n", "Smallest Int: ", smallest);
    printf("%-20s%20d\n", "Average Int: ", average);
    printf("%-20s%20d\n", "Count Above Avg: ", countAboveAverage); */
}
Data:        1        2        3       -3      -99      999       42       14       56       76       99 

Results:
Largest Int:                         999
Smallest Int:                        -99
Average Int:                         108
Address of main():            0x103ccaa90         
Address of data[]:            0x7ffeebf357e0      
Address of size:              0x7ffeebf357dc      
Address of largest():         0x103ccac60         
Address of largestNum:        0x7ffeebf357d8      
Address of smallest():        0x103ccacd0         
Address of smallestNum:       0x7ffeebf357d4      
Address of average():         0x103ccad40         
Address of averageNum:        0x7ffeebf357d0      
Address of printdata():       0x103ccad90         
Address of printrslts():      0x103ccadd0         
bash-3.2$ exit

Script done on Thu Sep  3 18:51:21 2020
